# Pipeline
stages:
  - test
  - build
  - mirror

# Testing
test:
  stage: test
  image: python:3.9
  script:
    - pip install -r requirements.txt
    - pytest
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" && $CI_PIPELINE_SOURCE == "push"'

# Building Docker image and pushing to Docker Hub
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t rmottanet/unchainedtext:latest .
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
    - docker push rmottanet/unchainedtext:latest
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main" && $CI_COMMIT_MESSAGE =~ /Merge branch/i'

# Mirroring on Github
mirror:
  stage: mirror
  script:
    - export REPO_NAME=$(echo $CI_PROJECT_PATH | cut -d'/' -f2)
    - git remote add github https://${GITHUB_TOKEN}@github.com/rmottanet/$REPO_NAME.git
    - git checkout -b main
    - git push --set-upstream github main
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main" && $CI_COMMIT_MESSAGE =~ /Merge branch/i'
